
workflows:
- name: resource-count
  replicas: 1
  task_queue: ServerCount

temporal:
  host: temporal-frontend.temporal.svc.cluster.local
  port: 7233
  namespace: default

dialogflow:
  project_id: paul-fmma
  language_code: en

discord: {}

resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 400m
    memory: 256Mi

image:
  tag: latest
  pullPolicy: Always
  repository: ghcr.io/turnbros/paul-go/paul-go

nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []

serviceAccount:
  name: paul
  create: true
  annotations: {}

podSecurityContext:
  fsGroup: 3240

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 3240

nodeSelector: {}
tolerations: []
affinity: {}