{{- range $workflow := .Values.workflows }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paul.fullname" $ }}-workflow-{{ regexReplaceAll "_" $workflow.name "-" }}-worker
  labels:
    paul.turnbros.app/role: worker
    paul.turnbros.app/component: workflow
    paul.turnbros.app/environment: prod-ish
    {{- include "paul.labels" $ | nindent 4 }}
spec:
  replicas: {{ $workflow.replicas }}
  selector:
    matchLabels:
      {{- include "paul.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "paul.selectorLabels" $ | nindent 8 }}
    spec:
    {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "paul.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command: ["start-worker"]
          args: ["-workflow", "{{ $workflow.name }}"]
          envFrom:
            - secretRef:
                name: {{ include "paul.fullname" $ }}-discord-token
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}