---
kind: ExternalSecret
apiVersion: kubernetes-client.io/v1
metadata:
  name: {{ include "paul.fullname" . }}-dialogflow-credentials
  labels:
    {{- include "paul.labels" . | nindent 4 }}
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: kubernetes-external-secrets
  data:
    - name: dialogflow_creds.json
      key: homestead-secrets/data/apps/paul/dialogflow
      property: credentials
---
kind: ExternalSecret
apiVersion: kubernetes-client.io/v1
metadata:
  name: {{ include "paul.fullname" . }}-discord-token
  labels:
    {{- include "paul.labels" . | nindent 4 }}
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: kubernetes-external-secrets
  data:
    - name: DISCORD_TOKEN
      key: homestead-secrets/data/apps/paul/discord
      property: token