---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "paul.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "paul.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "paul.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "paul.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "paul.serviceAccountName" . }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "paul.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - list
  - watch
  - create
  - update
  - patch
  - get
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
  - create
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "paul.serviceAccountName" . }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "paul.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "paul.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "paul.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io